# Generated by Django 4.2.6 on 2023-10-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
        ('main_app', '0003_rename_feed_feeding'),
    ]

    operations = [
    ]
